version: '3.8'

services:
  research-assistant:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: research-assistant
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/research_db
      - REDIS_URL=redis://redis:6379
      - VECTOR_DB_URL=http://weaviate:8080
      - DEBUG=false
      - LOG_LEVEL=INFO
    volumes:
      - ../logs:/app/logs
      - ../temp:/app/temp
    depends_on:
      - db
      - redis
      - weaviate
    networks:
      - research-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: research-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=research_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - research-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: research-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - research-network
    restart: unless-stopped

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: research-weaviate
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-openai
      - ENABLE_MODULES=text2vec-openai
      - OPENAI_APIKEY=${OPENAI_API_KEY}
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - research-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: research-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../static:/usr/share/nginx/html/static:ro
    depends_on:
      - research-assistant
    networks:
      - research-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  weaviate_data:

networks:
  research-network:
    driver: bridge